# Generated by Django 4.0 on 2022-04-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_subcategory_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
