# Generated by Django 4.0 on 2022-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=30000, max_digits=10),
        ),
    ]
