# Generated by Django 4.0 on 2022-04-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping',
        ),
    ]
